name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test -v ./...
  build:
    needs: test
    strategy:
      matrix:
        go-version: [1.18]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - run: go build -v ./...